name: Executar Todos os Testes

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  testes-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ServeRest-Cypress
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Criar diretório de relatórios
        run: mkdir -p cypress/test_reports

      - name: Executar testes Backend com Cypress
        run: npx cypress run --spec "cypress/e2e/backend/**/*.cy.js"

      - name: Mesclar relatórios Mochawesome
        run: npx mochawesome-merge cypress/test_reports/*.json > cypress/test_reports/backend-report.json

      - name: Gerar relatório HTML Mochawesome
        run: npx marge cypress/test_reports/backend-report.json -f backend-report -o cypress/test_reports

      - name: Fazer upload do relatório de testes Backend
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-backend
          path: ServeRest-Cypress/cypress/test_reports/**/*
  
  testes-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ServeRest-Cypress
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Criar diretório de relatórios
        run: mkdir -p cypress/test_reports

      - name: Executar testes Frontend com Cypress
        run: npx cypress run --spec "cypress/e2e/frontend/**/*.cy.js"

      - name: Mesclar relatórios Mochawesome
        run: npx mochawesome-merge cypress/test_reports/*.json > cypress/test_reports/frontend-report.json

      - name: Gerar relatório HTML Mochawesome
        run: npx marge cypress/test_reports/frontend-report.json -f frontend-report -o cypress/test_reports

      - name: Fazer upload do relatório de testes Frontend
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-frontend
          path: ServeRest-Cypress/cypress/test_reports/**/*

  testes-carga:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ServeRest-Cypress
    steps:
      - uses: actions/checkout@v4

      - name: Instalar K6
        run: |
          curl -s https://api.github.com/repos/grafana/k6/releases/latest | \
            grep "browser_download_url.*linux-amd64" | \
            cut -d '"' -f 4 | wget -qi -
          tar -xzf k6-v*-linux-amd64.tar.gz
          sudo mv k6-v*-linux-amd64/k6 /usr/local/bin

      - name: Criar diretório de relatórios
        run: mkdir -p cypress/test_reports/k6
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Gerar massa de dados
        run: |
          npx cypress run --spec ./cypress/k6/*.js

      - name: Executar teste de carga com K6
        run: |
          k6 run cypress/k6/scripts/api-load-test.js \
            --summary-export=cypress/test_reports/k6/load_result.json

      - name: Fazer upload do relatório de teste de carga
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-teste-carga
          path: ServeRest-Cypress/cypress/test_reports/k6/**/*

  resumo-relatorios:
    runs-on: ubuntu-latest
    needs: [testes-backend, testes-frontend, testes-carga]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: relatorio-testes-backend
          path: resumo/backend

      - uses: actions/download-artifact@v4
        with:
          name: relatorio-testes-frontend
          path: resumo/frontend

      - uses: actions/download-artifact@v4
        with:
          name: relatorio-teste-carga
          path: resumo/carga

      - name: Criar índice de resumo
        run: |
          echo "<html><body><h1>Resumo dos Testes</h1>" > resumo/index.html
          echo "<ul>" >> resumo/index.html
          echo "<li><a href='./backend/backend-report.html'>Relatório Backend</a></li>" >> resumo/index.html
          echo "<li><a href='./frontend/frontend-report.html'>Relatório Frontend</a></li>" >> resumo/index.html
          echo "<li><a href='./carga/load_result.json'>Relatório Teste de Carga</a></li>" >> resumo/index.html
          echo "</ul></body></html>" >> resumo/index.html

      - name: Fazer upload do resumo consolidado
        uses: actions/upload-artifact@v4
        with:
          name: resumo-testes
          path: resumo/**
